### ISSUE TITLE
Home Wizard Aircooler 

### ISSUE THREAD

**Issue by Pascal4Games** [dennis1804/homewizard-climate-hass#12]
Trying to add Aircooler unit but get the following from the logs. Is it possible to add this device?

Logger: homeassistant.config_entries
Source: custom_components/homewizard_climate/__init__.py:37
Integration: Homewizard Climate
First occurred: 11 augustus 2023 om 23:54:09 (2 occurrences)
Last logged: 12:04:27
Error setting up entry XXXX for homewizard_climate

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homewizard_climate/__init__.py", line 37, in async_setup_entry
    devices: list[HomeWizardClimateDevice] = await hass.async_add_executor_job(
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/homewizard_climate_ws/api/api.py", line 70, in get_devices
    devices_list = list(
                   ^^^^^
  File "/usr/local/lib/python3.11/site-packages/dataclasses_json/api.py", line 70, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dataclasses_json/core.py", line 219, in _decode_dataclass
    init_kwargs[field.name] = _decode_generic(field_type,
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dataclasses_json/core.py", line 308, in _decode_generic
    res = _decode_generic(type_arg, value, infer_missing)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dataclasses_json/core.py", line 271, in _decode_generic
    res = type_(value)
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 711, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 1128, in __new__
    raise ve_exc
ValueError: 'aircooler' is not a valid HomeWizardClimateDeviceType

**Comment by pascal4ajax** [comment]
When I add the aircooler to the websocket local respons from ./debug.sh

DEBUG:homewizard_climate_ws.api.api:Logging in to https://api.homewizardeasyonline.com/v1/auth/login with username XXXX
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.homewizardeasyonline.com:443
DEBUG:urllib3.connectionpool:https://api.homewizardeasyonline.com:443 "GET /v1/auth/login HTTP/1.1" 200 695
DEBUG:homewizard_climate_ws.api.api:Login (XXXX) status code: 200
DEBUG:homewizard_climate_ws.api.api:Login successful with token for username XXXX
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.homewizardeasyonline.com:443
DEBUG:urllib3.connectionpool:https://api.homewizardeasyonline.com:443 "GET /v1/auth/devices HTTP/1.1" 200 298
DEBUG:homewizard_climate_ws.api.api:Received 1 device(s) for user (XXXX), filtering the supported ones. supported_device_types: ['heaterfan', 'infraredheater', 'heater', 'fan', 'dehumidifier', 'airconditioner', 'aircooler']
DEBUG:homewizard_climate_ws.api.api:Creating 1 device(s) for user (XXXX): ['aircooler/3c39e7298dd6']
Air Cooler is an: aircooler
INFO:homewizard_climate_ws.ws.hw_websocket.aircooler/3c39e7298dd6:Connecting to websocket (wss://app-ws.homewizard.com/ws)
INFO:websocket:Websocket connected
DEBUG:homewizard_climate_ws.ws.hw_websocket.aircooler/3c39e7298dd6:Websocket opened
DEBUG:homewizard_climate_ws.ws.hw_websocket.aircooler/3c39e7298dd6:Sending message for command _hello: {"message_id": "hello", "token": "eyJhbGciOi...nqFC5Oel1w", "type": "hello", "source": "https://github.com/mepla/homewizard-climate-websocket", "compatibility": 4}
DEBUG:homewizard_climate_ws.ws.hw_websocket.aircooler/3c39e7298dd6:Received message: {"type":"response","message_id":"hello","status":200}
DEBUG:homewizard_climate_ws.ws.hw_websocket.aircooler/3c39e7298dd6:Received response update: {'type': 'response', 'message_id': 'hello', 'status': 200}
DEBUG:homewizard_climate_ws.ws.hw_websocket.aircooler/3c39e7298dd6:Auto responding to `hello` response with `subscribe`
DEBUG:homewizard_climate_ws.ws.hw_websocket.aircooler/3c39e7298dd6:Sending message for command _handle_response_update: {"type": "subscribe_device", "device": "aircooler/3c39e7298dd6", "message_id": "subscribe"}
DEBUG:homewizard_climate_ws.ws.hw_websocket.aircooler/3c39e7298dd6:Received message: {"type":"response","message_id":"subscribe","status":200,"details":"Tracking ID: 3281542615969027"}
DEBUG:homewizard_climate_ws.ws.hw_websocket.aircooler/3c39e7298dd6:Received response update: {'type': 'response', 'message_id': 'subscribe', 'status': 200, 'details': 'Tracking ID: 3281542615969027'}
DEBUG:homewizard_climate_ws.ws.hw_websocket.aircooler/3c39e7298dd6:Received message: {"type":"aircooler","device":"aircooler/3c39e7298dd6","state":{"power_on":false,"timer":0,"fan_speed":"low","mode":"sleep","cool":false,"oscillate":true,"mute":true,"warning":["water_level"]},"wifi_strength":0,"name":"Air Cooler","online":true,"version":"1.01","model":"1.0,HWCaircool","hardware_version":"1.00","wifi_ssid":"SoukupP Smart"}
DEBUG:homewizard_climate_ws.ws.hw_websocket.aircooler/3c39e7298dd6:Socket initialized.
DEBUG:homewizard_climate_ws.ws.hw_websocket.aircooler/3c39e7298dd6:Received full device update: {'type': 'aircooler', 'device': 'aircooler/3c39e7298dd6', 'state': {'power_on': False, 'timer': 0, 'fan_speed': 'low', 'mode': 'sleep', 'cool': False, 'oscillate': True, 'mute': True, 'warning': ['water_level']}, 'wifi_strength': 0, 'name': 'Air Cooler', 'online': True, 'version': '1.01', 'model': '1.0,HWCaircool', 'hardware_version': '1.00', 'wifi_ssid': 'SoukupP Smart'}
ERROR:websocket:error from callback <bound method HomeWizardClimateWebSocket._on_message of <homewizard_climate_ws.ws.hw_websocket.HomeWizardClimateWebSocket object at 0x7fb8729410>>: invalid literal for int() with base 10: 'low'
DEBUG:homewizard_climate_ws.ws.hw_websocket.aircooler/3c39e7298dd6:Socket closed. Code: None, message: None
DEBUG:homewizard_climate_ws.ws.hw_websocket.aircooler/3c39e7298dd6:Disconnect was explicitly requested, not attempting to reconnect

**Comment by dennis1804** [comment]
hi, i added it to the newest version of the websocket part. it will probably only turn on and off now, but my priorities are now more on a little rebuild of this integration then add new devices. 
I'll add the list you provided in here to the requirements for that aircooler and add it after the rebuild.
can you tell me which states are also present in this aircooler? like the different modes?

Kind regards,

**Comment by Pascal4Games** [comment]
Hallo, thanks for adding it to the websocket.
I have added aircooler the climate file, but since you will be rebuilding it you may not be able to use it.
Also make a change to the fan. 

https://github.com/Pascal4Games/homewizard-climate-hass/blob/master/custom_components/homewizard_climate/climate.py

Here is a list with the values of the air cooler:

Power_on: true/false [HVACMode.COOL, HVACMode.OFF]
timer: Value not yet tested but looks like number
fan_speed: low/med/high [FAN_LOW, 'med', FAN_HIGH] (FAN_MEDIUM does not work)
mode: sleep/manual/natural ['manual', PRESET_SLEEP, 'natural'] (PRESET_COMFORT/PRESET_ECO does not work)
cool: true/false
oscillate: true/false [SWING_HORIZONTAL, SWING_OFF]
mute: true/false
warning: null/unkown yet warning is likely if water tank is empty

**Comment by Pascal4Games** [comment]
Made in change for the aircooler in combination with the web socket.
It 's now possible to change if the device is fan only or cool.
