### ISSUE TITLE
Trying to update but getting "This version d906d76 for this integration can not be used with HACS"

### ISSUE THREAD

**Issue by figjamalba** [dennis1804/homewizard-climate-hass#21]
Trying to update to d906d76 from f4e371d in HACS. 

Core 2024.2.5
Supervisor 2024.02.1
Operating System 12.0
Frontend 20240207.1

The integration is for a Glass Panel Heater.

Any suggestions or just skip this version?

**Comment by Pascal4Games** [comment]
Go to hacs and then to the integration Homewizard Climate. In the right corner (3 dots above eather) press the button and then "download again". Restart home assistant. Still version f4e371d? 
Another option is to download it manual from github and put de homewziard_climate folder inside config/custom_components and then restart home assistant.

**Comment by figjamalba** [comment]
Thank you, this fixed it.
