### ISSUE TITLE
The version d906d76 for this integration can not be used with HACS.

### ISSUE THREAD

**Issue by Gerhard-TM** [dennis1804/homewizard-climate-hass#26]
When I try to download the integration in HACS: The version d906d76 for this integration can not be used with HACS.

HACS version : 2.0.0

**Comment by chrnico2** [comment]
> When I try to download the integration in HACS: The version [d906d76](https://github.com/dennis1804/homewizard-climate-hass/commit/d906d76561f3a28765aa44d5c3d500ad4bf83d30) for this integration can not be used with HACS.
> 
> HACS version : 2.0.0

Same problem

**Comment by Gertjuh** [comment]
Same error here.
