### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by nlscarter** [dennis1804/homewizard-climate-hass#3]
While installing, I get 2 blank text field inputs, I assumed this was for the princess app? I input email and password but got invalid_auth error. 
Does this work with Princess infra red panel heaters?
Thanks
Neal

**Comment by dennis1804** [comment]
Hi, yes these are for your homewizard climate account, ( same you would use for the app), top one is email, bottom is password

Kind regards,

**Comment by dennis1804** [comment]
you can also test the auth by downloading this repository:

https://github.com/dennis1804/homewizard-climate-websocket/tree/feature/debug-devices

in it is a debug.sh command which can log the devices that exist on your homewizard climate account.
you only need to edit the email and password which will be set in the debug.sh file.
requirements for the script is that you have python3 and pip3 running on your system.
