### ISSUE TITLE
Glas panel heater

### ISSUE THREAD

**Issue by eriky1993** [dennis1804/homewizard-climate-hass#6]
Heey,

i've got the (glas)panel heater. its working in the original app but on home assistant it's showing unavailable.
with the original app i can control it. 

---
Heey, 

ik heb de paneelverwarming. Home Assistant vindt hem via de inlog wat gelukt is. alleen geeft hij onbeschikbaar aan. in de climate app kan ik hem wel bedienen. doe ik ergens wat verkeerd?

--Erik

**Comment by diricxbart** [comment]
Hello @eriky1993,

I had the exact same issue and did a fix for this just yesterday.
The [pull-request](https://github.com/dennis1804/homewizard-climate-websocket/pull/3) to be merged in by @dennis1804, also this repo would need it's requirements version to the `homewizard-climate-ws` Python package bumped to include that bugfix.

So with a little patience, the issue you're experiencing should be solved ;-).

Bart

**Comment by dennis1804** [comment]
thanks again @diricxbart, did the update for the websocket and this plugin.
seems to work fine on the IR panel :)
